/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dabar;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Barang extends javax.swing.JFrame {

    /**
     * Creates new form Barang
     */
    public Barang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        idedit = new javax.swing.JTextField();
        nomor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jumedit = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        DeleteBarang = new javax.swing.JButton();
        barangtambah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EditBarang = new javax.swing.JButton();
        TambahBarang = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jumlahtambah = new javax.swing.JTextField();
        nabaredit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_databarang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 170, -1));
        getContentPane().add(idedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 240, 30));
        getContentPane().add(nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 240, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 170, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 400, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Nama Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 170, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 400, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Nama Barang");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 170, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Jumlah Barang");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("EDIT BARANG");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));
        getContentPane().add(jumedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 240, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setAlignmentY(1.0F);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 20, 570));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel3.setText("TAMBAH BARANG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        DeleteBarang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteBarang.setText("Delete");
        DeleteBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBarangMouseClicked(evt);
            }
        });
        DeleteBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBarangActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 160, -1));
        getContentPane().add(barangtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 240, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Jumlah Barang");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 170, -1));

        EditBarang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EditBarang.setText("Edit Barang");
        EditBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBarangMouseClicked(evt);
            }
        });
        EditBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBarangActionPerformed(evt);
            }
        });
        getContentPane().add(EditBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, 160, -1));

        TambahBarang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TambahBarang.setText("Tambah Barang");
        TambahBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TambahBarangMouseClicked(evt);
            }
        });
        TambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahBarangActionPerformed(evt);
            }
        });
        getContentPane().add(TambahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 400, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 400, 20));
        getContentPane().add(jumlahtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 240, 30));
        getContentPane().add(nabaredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 240, 30));

        jButton1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 910, 20));

        tb_databarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_databarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_databarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_databarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 400, 170));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("DATA BARANG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dabar/126423686-pink-wood-wall-plank-texture-or-background-pink-pastel-color-wood-wall-background-or-texture-wood-te.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        DefaultTableModel tableMode;
        Object [] row =  {"ID", "Nama Barang", "Jumlah Barang"};
        tableMode = new DefaultTableModel (null, row);
        tb_databarang.setModel(tableMode);
        
        try {
            Connection conn = (Connection) Dabar.koneksi.koneksiDB();
            Statement st = conn.createStatement();
            String sql = "SELECT * From barang";
            ResultSet set = st.executeQuery(sql);
            
            int a = 1;
                while (set.next()){
                    String Nomor = String.valueOf(a + tableMode.getRowCount());
                    String Nabar = set.getString("nama_barang");
                    String Jumlah = set.getString("jumlah_barang");
                    
                    String [] data = {Nomor, Nabar, Jumlah};
                    tableMode.addRow(data);
                }
        } catch (Exception e) {
        } idedit.enable(false);
    }//GEN-LAST:event_formWindowActivated

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void TambahBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahBarangMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_TambahBarangMouseClicked

    private void TambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahBarangActionPerformed
        // TODO add your handling code here:
        String id = nomor.getText();
        String nabar = barangtambah.getText();
        String jumbar = jumlahtambah.getText();

        if (nabar.equals("")| jumbar.equals("") ) {
            JOptionPane.showMessageDialog(null, "Pengisian Data Tidak Boleh Kosong!");

        }else {

            try {
                Connection kon = (Connection) Dabar.koneksi.koneksiDB();
                Statement st   = kon.createStatement();
                String sql     = "INSERT into barang (id, Nama Barang, Jumlah Barang) values ('"+id+"', '"+barangtambah+"', '"+jumlahtambah+"')";
                int set        = st.executeUpdate(sql);

                Bersih();

                this.setVisible(false);
                this.setVisible(true);

            } catch (SQLException | HeadlessException e) {
            }
        }
    }//GEN-LAST:event_TambahBarangActionPerformed

    private void DeleteBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBarangMouseClicked
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin Delete Barang?", "Konfirmasi Delete", JOptionPane.YES_NO_OPTION);

        if (ok == 0) {
            try {
                Connection kon = (Connection) Dabar.koneksi.koneksiDB();
                Statement st   = kon.createStatement();
                String sql     = "DELETE From barang where id='"+idedit.getText()+"'";
                int set        = st.executeUpdate(sql);

                Bersih();

            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_DeleteBarangMouseClicked

    private void DeleteBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBarangActionPerformed

    private void EditBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBarangMouseClicked
        // TODO add your handling code here:
        idedit.setText(tb_databarang.getValueAt(tb_databarang.getSelectedRow(),0).toString());
    }//GEN-LAST:event_EditBarangMouseClicked

    private void EditBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBarangActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin Edit Barang?", "Konfirmasi Edit", JOptionPane.YES_NO_OPTION);

        if (ok == 0) {
            try {
                Connection kon = (Connection) Dabar.koneksi.koneksiDB();
                Statement st   = kon.createStatement();
                String sql     = "UPDATE barang SET id ='"+idedit.getText()+"'where Nama Barang'"+nabaredit.getText()+"'where Jumlah Barang='"+jumedit.getText()+"'";
                int set        = st.executeUpdate(sql);

                Bersih();

            } catch (SQLException e) {
            }
            Bersih();
        }
    }//GEN-LAST:event_EditBarangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Admin hal = new Admin ();
        hal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tb_databarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_databarangMouseClicked
        // TODO add your handling code here:
         idedit.setText(tb_databarang.getValueAt(tb_databarang.getSelectedRow(),0).toString());
    }//GEN-LAST:event_tb_databarangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBarang;
    private javax.swing.JButton EditBarang;
    private javax.swing.JButton TambahBarang;
    private javax.swing.JTextField barangtambah;
    private javax.swing.JTextField idedit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jumedit;
    private javax.swing.JTextField jumlahtambah;
    private javax.swing.JTextField nabaredit;
    private javax.swing.JTextField nomor;
    private javax.swing.JTable tb_databarang;
    // End of variables declaration//GEN-END:variables

    private void Bersih() {
        idedit.setText("");
        nabaredit.setText("");
        jumedit.setText("");
        
    }
}
